# Generated by Django 5.2 on 2025-06-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["id"]},
        ),
    ]
